### ISSUE TITLE
Erro no Login - prioridade

### ISSUE THREAD

**Issue by cadgarcia** [System3D/steel4web#17]
https://youtu.be/vtLt4nK0J6o + https://youtu.be/am4UneEAXKE + https://youtu.be/YDyUncrzEFM

**Comment by cadgarcia** [comment]
https://youtu.be/vtLt4nK0J6o

**Comment by cadgarcia** [comment]
https://youtu.be/vtLt4nK0J6o

**Comment by tonetlds** [comment]
Era configuração do Apache.
Arquivo *httpd.conf* alterado de 8080 para 80
```
...
ServerName localhost:80
...
```
