### ISSUE TITLE
Prioridade - Gestor Lotes - erro qtde ao associar a lote existente

### ISSUE THREAD

**Issue by cadgarcia** [System3D/steel4web#25]
erro qtde ao associar a lote existente

https://youtu.be/PIxdBwGnzc0

**Comment by tonetlds** [comment]
Não estou conseguindo simular o erro.

**Comment by tonetlds** [comment]
Erro detectado...
![image](https://cloud.githubusercontent.com/assets/2693019/13321834/277b2e84-dbb0-11e5-9434-218226d90b6c.png)

Iniciando correções...
