### ISSUE TITLE
Prioridade - Gestor Lotes - não cria lote ao selecionar cjto

### ISSUE THREAD

**Issue by cadgarcia** [System3D/steel4web#47]

**Comment by tonetlds** [comment]
Testes em www.steel4web.com.br/**dev**/app _v1.1.3_

- Montar Lote
- Remover do Lote
- Associar ao Lote
- Remover Lote Inteiro

1. Chrome https://www.youtube.com/watch?v=iPmBvY-2iZk
2. Opera https://www.youtube.com/watch?v=iAFXY8oQ7vE
3. Firefox https://www.youtube.com/watch?v=I1lCI8Oam1A
4. Internet Explorer https://www.youtube.com/watch?v=PK5vw7nJAnE
