### ISSUE TITLE
Gestor de Lotes - Conjuntos

### ISSUE THREAD

**Issue by cadgarcia** [System3D/steel4web#67]
Acrescer colunas kg Unit. e kg Total + Label Cjtos Imp.

https://www.youtube.com/watch?v=Y3BzfqJN8fo

**Comment by tonetlds** [comment]
Gestor de Lotes / Conjuntos
- [ ] Inverter posição das colunas **Ícone** e **Tratamento**
- [ ] Adicionar coluna **Kg Unitário**
- [ ] Adicionar coluna **Kg Total**

**Comment by tonetlds** [comment]
Gestor de Lotes / Conjuntos
- [x] Inverter posição das colunas **Ícone** e **Tratamento**
- [x] Adicionar coluna **Kg Unitário**
- [x] Adicionar coluna **Kg Total**
